Repository stratis-storage/stratis-cli, pull requests merged in 2018-06, with the labels that each got.

#149 Catch all exception when trying to interpret an error
  src/stratis_cli/_error_reporting.py
Labels: review-final

#152 Add completion function for Zsh
  shell-completion/zsh/_stratis
Labels: review-prelim

#153 Move bash shell completion under shell-completion/bash
  shell-completion/bash/stratis
Labels: review-final, trivial
